id: opecha:P000412
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4244
  title: རྒྱ་གཞུང་སྐོར་གྱི་ཚད་མ་ཕྱོགས་བསྒྲིགས།
  volume:
    2b9ea3e1744146539a8658b6413f6b3b:
      image_group_id: I1KG4956
      title: Volume 1 of rgya gzhung skor gyi tshad ma phyogs bsgrigs/
      volume_number: 1
      total_pages: 472
    a851888a8b79418b86a403903c726bfe:
      image_group_id: I1KG4957
      title: Volume 2 of rgya gzhung skor gyi tshad ma phyogs bsgrigs/
      volume_number: 2
      total_pages: 452
  author: ''
ebook_metadata:
  title: རྒྱ་གཞུང་སྐོར་གྱི་ཚད་མ་ཕྱོགས་བསྒྲིགས།
  author: ''
  sku: P000412
  cover: cover.jpg
  layers:
  - pagination
